---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/backend

patchesJson6902:
- path: base/backend/deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: backend
    version: v1

...